name: Pull request
on:
  pull_request:
    branches:
      - develop
      - main
      - "flutter/**"
permissions:
  checks: write
  contents: write
jobs:
  flutter-job:
    name: Run Flutter test and analyzer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0
        with:
          channel: "stable"
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run Format
        run: dart format --set-exit-if-changed .

      - name: Run Analyzer
        run: flutter analyze .
